services:
  task_10:
    container_name: task_10_container
    image: task_10_image
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db_task_10
    ports:
      - "${SWAGGER_PORT_OUT}:${SWAGGER_PORT_IN}"

  db_task_10:
    container_name: postgres_container_task_10
    image: postgres:15
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    env_file:
      - .env


volumes:
  postgres_data:
